server:
  port: 8014
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/postgres
    username: test
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: test
        format_sql: true
        show_sql: true
  liquibase:
    enabled: true
    default-schema: test
    change-log: classpath:liquibase/db.changelog-master.yml